### ISSUE TITLE
Using Flat module to flatten circular objects crashes stack 

### ISSUE THREAD

**Issue by sgrasso** [jessie-codes/good-gelf#23]
Flat doesn't handle circular references in objects correctly. This creates node to blow up running out of heap memory when trying to log.  

See Flat issue here.
[https://github.com/hughsk/flat/issues/24](https://github.com/hughsk/flat/issues/24)

Perhaps just using the fast-safe-stringify to do a replacer prior to passing it to Flat in the Flatten method.

From fast-safe-stringify's README...
```
const safeStringify = require('fast-safe-stringify')

function replacer(key, value) {
  console.log('Key:', JSON.stringify(key), 'Value:', JSON.stringify(value))
  // Remove the circular structure
  if (value === '[Circular]') {
    return
  }
  return value
}
const serialized = safeStringify(o, replacer, 2)
// Key: "" Value: {"a":1,"o":"[Circular]"}
// Key: "a" Value: 1
// Key: "o" Value: "[Circular]"
```

**Comment by jessie-codes** [comment]
Fixed in commit d7ffb3a3378ad0196c2aa0680dfba8b7aa9951f6
